version: '3'
services:
  api:
    build: .
    container_name: land-registry-pipeline
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    command: uvicorn src.api.main_yearly:app --host 0.0.0.0 --port 8000 --reload

  pipeline:
    build: .
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    command: python -m src.pipeline.beam_pipeline

  test:
    build: .
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: pytest tests/