version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.1.0
  kubernetes: circleci/kubernetes@1.3.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest tests/

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize
      - kubernetes/create-or-update-resource:
          resource-file: k8s/deployment.yaml
          resource-name: deployment/land-registry-pipeline
      - kubernetes/create-or-update-resource:
          resource-file: k8s/service.yaml
          resource-name: service/land-registry-pipeline
      - kubernetes/create-or-update-resource:
          resource-file: k8s/cronjob.yaml
          resource-name: cronjob/land-registry-pipeline-cron

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main