version: 2.1

orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@2.1.4

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest test/

  build-and-push-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: olayanjuibraheem/land-registry-pipeline
          tag: ${CIRCLE_SHA1}
      - docker/push:
          image: olayanjuibraheem/land-registry-pipeline
          tag: ${CIRCLE_SHA1}
run-pipeline:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Run API
          command: uvicorn src.api.main_yearly:app --reload
      - run:
          name: Run pipeline
          command: python src/pipeline/beam_pipeline.py --input_file input.csv --output_file output.json

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - build-and-push-docker:
          requires:
            - build-and-test
          context: docker-hub-creds
          filters:
            branches:
              only: main