version: 2.1

orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@2.1.4

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest test/
  build-and-push-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # this env var must be set within the project
      - run:
          name: Process template file
          environment:
            # Environment variables would typically be served via a context
            FOO: bar
            PROVIDER: circleci
          command: |
            circleci env subst < template.json > deploy.json
            cat deploy.json
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: olayanjuibraheem/land-registry-pipeline
          tag: ${CIRCLE_SHA1}
      - docker/push:
          image: olayanjuibraheem/land-registry-pipeline
          tag: ${CIRCLE_SHA1}
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - build-and-push-docker:
          requires:
            - build-and-test
          filters:
            branches:
              only: main

